# Simple configuration to test HTTP server functionality

version = "v1"

[logging]
level = "debug"
format = "text"

[[listeners]]
id = "http-default"
address = ":8080"
type = "http"

[listeners.http]
read_timeout = "5s"
write_timeout = "10s"

[[endpoints]]
id = "ep-default"
listener_id = "http-default"

[[endpoints.routes]]
app_id = "app-hello"
[endpoints.routes.http]
path_prefix = "/hello"

[[endpoints.routes]]
app_id = "app-static"
[endpoints.routes.http]
path_prefix = "/static"

[[apps]]
id = "app-hello"

[apps.script]
[apps.script.risor]
code = """
	import "http"
	import "json"

	func handler(req http.Request) http.Response {
		return http.Response{
			StatusCode: 200,
			Body: "Hello, World!",
		}
	}

	export default: handler
"""

# Add the missing app-static reference that was causing the validation error
[[apps]]
id = "app-static"

[apps.script]
[apps.script.static_data]
data = { message = "Static app content" }

[apps.script.risor]
code = """
	import "http"
	import "json"

	func handler(req http.Request) http.Response {
		return http.Response{
			StatusCode: 200,
			Body: req.static_data.message,
		}
	}

	export default: handler
"""