# FireLynx Configuration Example: Preset-Based Logging
#
# This configuration demonstrates the preset-based logging system
# for common logging scenarios with minimal configuration.
#
# Compare this setup with logging-full.toml which shows manual field configuration.
# This example uses presets to achieve similar functionality with fewer lines.

version = "v1"

# HTTP Listener Configuration
[[listeners]]
id = "http"
address = ":8080"
type = "http"


# Endpoint Configuration
[[endpoints]]
id = "main"
listener_id = "http"

# Standard Logger Setup - includes method, path, status, client IP, and duration
[[endpoints.middlewares]]
id = "logger"
type = "console_logger"

[endpoints.middlewares.console_logger]
preset = "standard"                           # Includes method, path, status, client IP, duration
output = "stdout"                             # Can be "stderr" or file path like "/tmp/app.log"
exclude_paths = ["/health", "/metrics"]      # Skip health checks

[endpoints.middlewares.console_logger.options]
format = "json"
level = "info"

# Route Configuration
[[endpoints.routes]]
app_id = "hello"
[endpoints.routes.http]
path_prefix = "/"

# Application Definition
[[apps]]
id = "hello"
type = "echo"
[apps.echo]
response = "Hello from FireLynx!"