version = "v1"

[[listeners]]
id = "http"
address = ":8080"
type = "http"

[[endpoints]]
id = "main"
listener_id = "http"

[[endpoints.routes]]
app_id = "echo"
[endpoints.routes.http]
path_prefix = "/"

[[apps]]
id = "echo"
[apps.echo]
response = "Hello, World!"