name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "latest"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Display Go version
        run: go version

      - name: go mod tidy (fails if changes are needed)
        run: go mod tidy --diff

      - name: go vet
        run: go vet ./...

      - name: Run protogen and check for uncommitted changes in gen
        run: |
          make protogen
          if ! git diff --exit-code -- gen; then
            echo "::error file=gen::Protobuf files are out of date. Please run 'make protogen' and commit the changes."
            exit 1
          fi

      - name: Go test (short)
        run: make test-short

      - name: Go test (all)
        run: make test-all
